/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.uts1;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author BIMA
 */
public class UTS extends javax.swing.JFrame {

    String pilih;
    String sistem1;
    String masukan;
//    String sistem2;
//    String sistem3;
    public UTS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbatu = new javax.swing.JRadioButton();
        rgunting = new javax.swing.JRadioButton();
        rkertas = new javax.swing.JRadioButton();
        bmulai = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Lpilih = new javax.swing.JLabel();
        rkertas1 = new javax.swing.JRadioButton();
        rbatu1 = new javax.swing.JRadioButton();
        rgunting1 = new javax.swing.JRadioButton();
        rbatu2 = new javax.swing.JRadioButton();
        rgunting2 = new javax.swing.JRadioButton();
        rkertas2 = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PERMAINAN BATU GUNTING KERTAS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(57, 57, 57))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("SILAHKAN PILIH SALAH SATU DIBAWAH:");

        buttonGroup1.add(rbatu);
        rbatu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbatu.setText("BATU1");
        rbatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbatuActionPerformed(evt);
            }
        });

        buttonGroup1.add(rgunting);
        rgunting.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rgunting.setText("GUNTING1");

        buttonGroup1.add(rkertas);
        rkertas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rkertas.setText("KERTAS1");
        rkertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkertasActionPerformed(evt);
            }
        });

        bmulai.setText("MULAI");
        bmulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulaiActionPerformed(evt);
            }
        });

        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("VS AI");

        buttonGroup1.add(rkertas1);
        rkertas1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rkertas1.setText("KERTAS2");
        rkertas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkertas1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbatu1);
        rbatu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbatu1.setText("BATU2");
        rbatu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbatu1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rgunting1);
        rgunting1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rgunting1.setText("GUNTING2");

        buttonGroup1.add(rbatu2);
        rbatu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbatu2.setText("BATU3");
        rbatu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbatu2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rgunting2);
        rgunting2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rgunting2.setText("GUNTING3");

        buttonGroup1.add(rkertas2);
        rkertas2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rkertas2.setText("KERTAS3");
        rkertas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rkertas2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(85, 85, 85))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbatu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbatu1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbatu2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lpilih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rgunting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rgunting1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rgunting2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rkertas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rkertas1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rkertas2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(43, 43, 43))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(bmulai, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbatu)
                    .addComponent(rgunting)
                    .addComponent(rkertas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbatu1)
                    .addComponent(rgunting1)
                    .addComponent(rkertas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbatu2)
                    .addComponent(rgunting2)
                    .addComponent(rkertas2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lpilih, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bmulai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbatuActionPerformed

    private void rkertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkertasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rkertasActionPerformed

    private void bmulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulaiActionPerformed
        
        if (rbatu.isSelected()){
//            jPanel2.setBackground(Color.GREEN);
            pilih ="BATU";  
            sistem1="BATU";
            Lpilih.setText(pilih);
          JOptionPane.showMessageDialog(this,"ANDA : " +pilih + "\nSISTEM : " +sistem1 + "\nHasil : ANDA SERI");
        }
        if (rkertas.isSelected()){
//             jPanel2.setBackground(Color.YELLOW);
            pilih ="KERTAS";
            sistem1="BATU";
              Lpilih.setText(pilih);
           JOptionPane.showMessageDialog(this,"ANDA : " +pilih + "\nSISTEM : " +sistem1 + "\nHasil : ANDA MENANG");
        }
        if (rgunting.isSelected()){
            pilih ="GUNTING";
            sistem1="BATU";
              Lpilih.setText(pilih);
          JOptionPane.showMessageDialog(this,"ANDA : " +pilih + "\nSISTEM : " +sistem1 + "\nHasil : ANDA KALAH");
          
        }
        if (rgunting1.isSelected()){
            pilih ="GUNTING";
            sistem1="GUNTING";
              Lpilih.setText(pilih);
           JOptionPane.showMessageDialog(this,"ANDA : " +pilih + "\nSISTEM : " +sistem1 + "\nHasil : ANDA SERI");
   
        }
        if (rbatu1.isSelected()){
            pilih ="BATU";
            sistem1="GUNTING";
              Lpilih.setText(pilih);
             JOptionPane.showMessageDialog(this,"ANDA : " +pilih + "\nSISTEM : " +sistem1 + "\nHasil : ANDA MENANG");
        }
        if (rkertas1.isSelected()){
            pilih ="KERTAS";
            sistem1="GUNTING";
              Lpilih.setText(pilih);
             JOptionPane.showMessageDialog(this,"ANDA : " +pilih + "\nSISTEM : " +sistem1 + "\nHasil : ANDA KALAH");
        }
        if (rbatu2.isSelected()){
            pilih ="BATU";
            sistem1="KERTAS";
              Lpilih.setText(pilih);
             JOptionPane.showMessageDialog(this,"ANDA : " +pilih + "\nSISTEM : " +sistem1 + "\nHasil : ANDA KALAH");
        }
        if (rkertas2.isSelected()){
            pilih ="KERTAS";
            sistem1="KERTAS";
              Lpilih.setText(pilih);
            JOptionPane.showMessageDialog(this,"ANDA : " +pilih + "\nSISTEM : " +sistem1 + "\nHasil : ANDA SERI");
        }
        if (rgunting2.isSelected()){
            pilih ="GUNTING";
            sistem1="KERTAS";
              Lpilih.setText(pilih);
            JOptionPane.showMessageDialog(this,"ANDA : " +pilih + "\nSISTEM : " +sistem1 + "\nHasil : ANDA MENANG");
        }
        
//           = cpilih.getSelectedIndex();
//     if(masukan==1){
//         jPanel2.setBackground(Color.GREEN);
//         jPanel4.setBackground(Color.GREEN);
//        
//
//     }   
         
    }//GEN-LAST:event_bmulaiActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bhapusActionPerformed

    private void rkertas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkertas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rkertas1ActionPerformed

    private void rbatu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbatu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbatu1ActionPerformed

    private void rbatu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbatu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbatu2ActionPerformed

    private void rkertas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rkertas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rkertas2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UTS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lpilih;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bmulai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rbatu;
    private javax.swing.JRadioButton rbatu1;
    private javax.swing.JRadioButton rbatu2;
    private javax.swing.JRadioButton rgunting;
    private javax.swing.JRadioButton rgunting1;
    private javax.swing.JRadioButton rgunting2;
    private javax.swing.JRadioButton rkertas;
    private javax.swing.JRadioButton rkertas1;
    private javax.swing.JRadioButton rkertas2;
    // End of variables declaration//GEN-END:variables
}
